import HeroImg from "@/public/planty_gero.jpeg";
import CotactUsImg from "@/public/contactus.jpeg";
import Phone from "@/public/phone.jpeg";
import AboutUs from "@/public/AboutUS.jpeg";
import Mission1 from "@/public/mission1.jpeg";
import Mission2 from "@/public/mission2.jpeg";
import Mission3 from "@/public/mission3.jpeg";
import Banayan from "@/public/banayan.webp";
import Amla from "@/public/amla.jpeg";
import Ashoka from "@/public/Ashoka.jpeg";
import Frangipani from "@/public/Frangipani.jpeg";
import Gulmohar from "@/public/Gulmohar.jpeg";
import Banana from "@/public/Banana.webp";
import Christmas from "@/public/christmas.webp";
import Coconut from "@/public/coconut.webp";
import Hibiscus from "@/public/hibiscus.webp";
import Mango from "@/public/Mango.webp";
import Neem from "@/public/Neem.webp";
import Pine from "@/public/pine.jpeg";
import Tulip from "@/public/tulip.jpeg";
import Tulsi from "@/public/Tulsi.jpeg";

export { HeroImg, CotactUsImg, Phone, AboutUs, Mission1, Mission2, Mission3, Banayan, Amla, Ashoka, Frangipani, Gulmohar, Banana, Christmas, Coconut, Hibiscus, Mango, Neem, Pine, Tulip, Tulsi};
